launchableinc/nose-launchable

launchable/plugin.py

Add a new option not to suppress errors when running a nose-launchable plugin. If you set `LAUNCHABLE_RAISE_ERROR` environment variable, errors are not suppressed.
Even if a KeyError occurred, the test does not stop.
```
KeyError: 'LAUNCHABLE_TOKEN'
test1.func_tests(1,) ... func_test1
ok
test1.func_tests(2,) ... func_test2
ok
test1.func_tests(3,) ... func_test3
ok
test1.func_tests(4,) ... func_test4
ok
test1.func_tests(5,) ... func_test5
ok
----------------------------------------------------------------------
Ran 5 tests in 0.001s
OK
```
The test execution stops when it encounters an error
```
raise KeyError(key) from None
KeyError: 'LAUNCHABLE_TOKEN'
```

Add a raise error option not to suppress errors

---

launchable/version.py

We released v0.0.9-alpha for our PAP customer. I release v0.1.0-alpha for https://github.com/launchableinc/rocket-car integration.
I will remove `-alpha` after I succeed to integrate to `rocket-car`.

Bump up to v0.1.0-alpha

---

launchable/plugin.py

@shuheiktgw  I reopen https://github.com/launchableinc/nose-launchable/pull/10. Sorry for confusing you.

Reopen "Change test_name's formart to file_path#class#func"

---

launchable/manager.py
tests/test_manager.py

Right now we use a module name as a testName for inference but depending on a file structure module name can be duplicated. As a result, when reordering, one test case may override others. Ref: https://github.com/launchableinc/nose-launchable/blob/main/launchable/manager.py#L65
In order to avoid that, I'll use a `relative_file_path#module_name` when inferencing.

Use a unique module name for the inference

---

launchable/plugin.py

I've noticed with the current rule, `testName` can be duplicated when a module contains two test classes with the same test name. Here is an example:
```
class TestClass1(unittest.TestCase):
def test1(self):
self.assertEqual(1, 1)
class TestClass2(unittest.TestCase):
def test1(self):
self.assertEqual(1, 1)
```
The above example outputs the same testName since the current testName uses `path#module#function` so it outputs `path#module#test1` twice. I fixed the testName to add a class name if the context is a class. So the same example outputs `path#module#TestClass1.test1`, `path#module#TestClass2.test1`.

Fix test result test name to include a class name

---

launchable/manager.py
launchable/plugin.py
tests/test_manager.py

Right now, we blindly split a test id with `.` like below:
```
ids = t.test.id().split(".")
```
but it does not work if a generator test's argument contains `.`. For example:
```
def test_evens():
for s in ["0.0", "1.0", "2.0"]:
yield check_true, s
def check_true(s):
assert s == s
```
[The xunit plugin handles the problem using a regular expression](https://github.com/nose-devs/nose/blob/master/nose/plugins/xunit.py#L66) so let's use it for nose-launchable too.

Fix a testName for generator tests

---

nose_launchable/client.py
tests/test_client.py

Fix the inference body to send an actual test session id

Fix the inference body to send an actual test session id

---

nose_launchable/client.py
nose_launchable/plugin.py
tests/test_client.py
tests/test_manager.py

Modify the nose-launchable plugin so that it closes a test session once it's finished uploading test cases.

Add a functionality to close a test session

---

requirements.txt

Updated the requirement lower bound to 1.5.5.

Update the launchable cli requirement

---

README.md
README.rst
nose_launchable/plugin.py

Newly added the `read-only` mode to the plugin, which only uploads test results to the Launchable server.

Add record-only mode

---

README.md
nose_launchable/client.py
nose_launchable/plugin.py
requirements.txt
tests/test_client.py

This PR defines a new flag called `launchable-subset-options` which is used to hand in Launchable CLI options directly from nose-launchable. With this change, customers can use the latest CLI options without defining new nose-launchable flags.

[ENG-89] Add launchable-subset-options flag

---

nose_launchable/plugin.py

Right now, we initialize `self._uploader` after calling `self._uploader.start()` but if the start method failed, self._uploader is never initialized. Instead of that, we initialize both `self._client` and `self._uploader` in the `__init__` and call the start methods later.

[ENG-98] Fix the plugin initialization order

---

nose_launchable/client.py
nose_launchable/plugin.py
nose_launchable/protecter.py

A customer reported that when the token is not set, we make nose fail hard. This shouldn't be.
This change makes that behaviour more graceful.
```
File "/usr/lib/python3/dist-packages/nose/config.py", line 590, in getParser
self.plugins.loadPlugins()
File "/usr/lib/python3/dist-packages/nose/plugins/manager.py", line 400, in loadPlugins
plug = plugcls()
File "/mtee-env/lib/python3.7/site-packages/nose_launchable/plugin.py", line 29, in __init__
self._client = LaunchableClientFactory.prepare()
File "/mtee-env/lib/python3.7/site-packages/nose_launchable/client.py", line 17, in prepare
url, org, wp, token = cls._parse_options()
File "/mtee-env/lib/python3.7/site-packages/nose_launchable/client.py", line 25, in _parse_options
_, user, _ = token.split(":", 2)
```

Improved the graceful fallback

---

nose_launchable/plugin.py

`self._uploader.start()` should come after `self._client.start(self.build_number)` since `self._client.start` sets a test session id in it.

Change the begin process

---

nose_launchable/plugin.py

Subset options should not be required unless subset is enabled.

Fix a bug with the record only flag

---

nose_launchable/manager.py
nose_launchable/plugin.py
tests/test_manager.py

We used to reorder tests even when subsetting but this breaks our customers' test environment. To avoid that, we disabled reordering when subsetting.

Disable reordering when subsetting

---

nose_launchable/client.py
tests/test_client.py

Add retry when a request failed. I didn't include 'POST' intentionally since POST is not usually idempotent.

Retry when a request failed

---

nose_launchable/manager.py
tests/test_manager.py

The current implementation sends contains test files to the subset endpoint even if it does not contain any tests. This is problematic especially when a user uses wantFunction/wantMethod interfaces to choose tests dynamically. For example, the Attrib plugin uses the interfaces and removes some tests.
To avoid that, I implemented the `is_empty` method which checks if a test file contains any test functions (or methods) recursively. With that change, the nose-launchable stop sending those empty test files to the subset endpoint.

Remove empty files from a subset request

---

nose_launchable/manager.py

One of our customers reported an issue that nose-launchable didn't stop parsing tree when it reached a method and executed it when during prepareTest. To avoid that I added logic to stop parsing the tree when it reached a method. In addition, I slightly changed the code by replacing `type(getattr(suite, "context", None)) is FunctionType` with `inspect.isfunction`.

[ENG-231] Stop parsing the test tree when reaching a method

---

nose_launchable/client.py
tests/test_client.py

[launchableinc/cli](https://github.com/launchableinc/cli) outputs session `builds/{build number}/test_sessions/{test session id}` format. like below)
```
$ launchable record session --build cli
builds/cli/test_sessions/310
```
However, nose-launchable handle test session id as `test_sessions/{test session id}`, the cli will fail to parse session https://github.com/launchableinc/cli/blob/1df90eb8ffe42ae6f7deb3f2e1fb6482ec8613f4/launchable/utils/session.py#L102-L111. So, I fixed it. 
Before fixing it, the cli only used the base so this issue didn't become a problem https://github.com/launchableinc/cli/blob/1df90eb8ffe42ae6f7deb3f2e1fb6482ec8613f4/launchable/commands/subset.py#L189-L191

align test session id format with cli command

---

nose_launchable/case_event.py
nose_launchable/plugin.py

addSkip method in nose plugin is already deprecated ref: https://nose.readthedocs.io/en/latest/plugins/interface.html#nose.plugins.base.IPluginInterface.addSkip
And skipped tests will are called to an addError method. 
> Warning DEPRECATED – check error class in addError instead
So, I fixed to check error type and when the error is an unittest.caseSkipTest or a nose.plugin.skip.SkipTest, we report the test case as staus skipped.
If the user uses an old python, the type will be `unittest2.case.SkipTest`. But we don't support such an old python. I don't care it, for now.
- add skip status
- support skip test

fix support skip test case

---

.github/workflows/test.yaml
pytest.ini
tests/test_protecter.py

set launchable config

---

.github/workflows/e2e.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml

- Update setup-python to v4. https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-python
- Fix Ubuntu-latest to ubuntu-20.04 since the current `ubuntu-latest` is `ubuntu-22.04` which does not support Python3.5 and 3.6.
- See below for Python version and OS support.
- https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

change ubuntu to 20.04 to support Python 3.5 and 3.6

---

.github/workflows/test.yaml

See
https://docs.launchableinc.com/sending-data-to-launchable/migration-to-github-oidc-auth.

Migrate to the new GitHub OIDC auth

---

nose_launchable/plugin.py
tests/test_client.py

In some cases, a test attribute of the test (`test.test`) isn't set. 
However, [get_test_path](https://github.com/launchableinc/nose-launchable/blob/bdc5615e3f84c25c59441cd471b6f9d5e7b3fb8d/nose_launchable/manager.py#L133) method calls a `test` attribute to make test path. Then, happened error `AttributeError: 'ContextSuite' object has no attribute 'test'`. 
So, I added validation and logging when it happens.

check test attributes

---

.github/workflows/e2e.yaml
.github/workflows/test.yaml

Our e2e CI sometimes failed to install the dependencies phase. 
So, I introduced a retry action

Retry setup phase

---

.github/workflows/test.yaml
requirements.txt

Because the secrets value couldn't load, the launchable command failed in https://github.com/launchableinc/nose-launchable/pull/71 
So, I cherry-picked the commit and updated support Python versions

Update nose3 to pynose

---

.github/workflows/publish.yaml

PyPI requires API token authentication now when we publish to PyPI. So, issued a token and updated to use it

update api token authentication
